### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by FabianTerhorst** [UglyTroLL/Swicon#1]
I get a "clang: error: linker command failed with exit code 1 (use -v to see invocation)" when i build my project with ..."pod 'Swicon', '~> 0.88'"... in my podfile.

**Comment by UglyTroLL** [comment]
@FabianTerhorst, can you provide more error logs (like use -v) to see which part actually went wrong?
